# Generated by Django 4.2.1 on 2023-05-30 20:33

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=255, verbose_name='Введите поисковый запрос')),
                ('year_start', models.CharField(max_length=255, verbose_name='Введите год начала периода отчета')),
                ('year_end', models.CharField(max_length=255, verbose_name='Введите год окончания периода отчета')),
                ('ktru_plots', models.BooleanField(verbose_name='Хотите ли вы посмотреть данные по закупкам товаров содержащих в КТРУ данные кодовые слова? ')),
                ('customers_plots', models.BooleanField(verbose_name='Хотите посмотреть данные по заказчикам, подчиненным Министерству Здравоохранения РФ')),
                ('regions_plots', models.BooleanField(verbose_name='Хотите ли вы получить распределение по закупкам изделий произведенных в РФ и импортных в регионах')),
                ('mnn_plots', models.BooleanField(verbose_name='Хотите ли вы получить данные по МНН закупаемых леканственных средств, содержащих данные кодовые слова?')),
                ('parse_data', models.BooleanField(verbose_name='Хотите ли вы выгружать данные с сайта?')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.order_cat')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('regular', 'regular'), ('subscriber', 'subscriber'), ('moderator', 'moderator')], default='regular', max_length=100)),
                ('payed_orders', models.PositiveSmallIntegerField(blank=True, default='1', verbose_name='Кол-во оплаченных заказов')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
